### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Cry2Loud** [jer-irl/update_ezflash_cheats#1]
PS C:\Users\Sam\Downloads\update_ezflash_cheats-main\update_ezflash_cheats-main> python update_ezflash_cheats.py patch -c "C:\Users\Sam\Downloads\omegacheatlibrary (1)\CHEAT" -d "C:\Users\Sam\Downloads\Nintendo - Game Boy Advance (20240325-224624)\Nintendo - Game Boy Advance (20240325-224624).dat" -l "C:\Users\Sam\Downloads\libretro-database-master\libretro-database-master"
Traceback (most recent call last):
  File "C:\Users\Sam\Downloads\update_ezflash_cheats-main\update_ezflash_cheats-main\update_ezflash_cheats.py", line 345, in <module>
    main()
  File "C:\Users\Sam\Downloads\update_ezflash_cheats-main\update_ezflash_cheats-main\update_ezflash_cheats.py", line 341, in main
    args.main(args)
  File "C:\Users\Sam\Downloads\update_ezflash_cheats-main\update_ezflash_cheats-main\update_ezflash_cheats.py", line 276, in main_patch
    patch(ezflash_cheats_path, datfile_path, libretro_database_path)
  File "C:\Users\Sam\Downloads\update_ezflash_cheats-main\update_ezflash_cheats-main\update_ezflash_cheats.py", line 263, in patch
    patch_ezflash_cht_file(target_cheat_file_path, libretro_cheat_file_path)
  File "C:\Users\Sam\Downloads\update_ezflash_cheats-main\update_ezflash_cheats-main\update_ezflash_cheats.py", line 195, in patch_ezflash_cht_file
    libretro_cheats = parse_libretro_cheats_from_file(libretro_cht_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sam\Downloads\update_ezflash_cheats-main\update_ezflash_cheats-main\update_ezflash_cheats.py", line 116, in parse_libretro_cheats_from_file
    key_name, key_type = key.split("_")
    ^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by jer-irl** [comment]
Good find, it looks like in the libretto database there are a few typos.  I've corrected them in a pull request.  You can download the pull request and use that instead of the master branch, or make the two changes to your downloaded master branch version.  Either should work, let me know if this doesn't work!
https://github.com/libretro/libretro-database/pull/1439

**Comment by jer-irl** [comment]
This was merged into the database, can you try again when able?

**Comment by Cry2Loud** [comment]
Jeremy, it worked! you have maybe saved the ezflash cheat community! thank you so so much!

**Comment by jer-irl** [comment]
I’m glad it works, and I hope you find it helpful!
